### ISSUE TITLE
Feature Request: Skip All Vertical Videos Such As "YouTube Shorts"

### ISSUE THREAD

**Issue by AceFrahm** [Elijas/auto-youtube-subscription-playlist-2#124] opened 2023-07-20 04:47 UTC
I have found that ALL YouTube Short are completely worthless content, but YouTube's algorithm is forcing creators to cave in to creating them.  

Can this google sheets spreadsheet be made to exclude all of those shorts on every channel that I otherwise do want to follow?

**Comment by eatsmarter-benny** [comment] 2024-02-05 06:47
This is a duplicate of the older request #120.

**Closed** 2024-02-21 03:30 UTC
