### ISSUE TITLE
TypeError: Second argument to Function.prototype.apply must be an array. (ligne 45, fichier "Code")

### ISSUE THREAD

**Issue by Flavien06** [Elijas/auto-youtube-subscription-playlist-2#23] opened 2018-02-20 17:53 UTC
Hi
I use the script for some days
It worked for the first few days and without changing anything I have the following error:

> TypeError: Second argument to Function.prototype.apply must be an array. (ligne 45, fichier "Code")

**Comment by Elijas** [comment] 2018-02-20 19:52
Just making sure if you did this already:
Resources > Developers Console Project > Click the link to your API console project > On the left, APIs & Auth > APIs > YouTube Data API > Enable API

**Comment by Flavien06** [comment] 2018-02-20 20:18
Yes, I have already activated "YouTube Data API v3".

**Comment by deepfriedmind** [comment] 2019-03-17 17:07
I've been getting the same error since a few days ago. Did you find a fix?

**Comment by Fabian42** [comment] 2019-03-17 19:23
No. But maybe this means that something about the YouTube API changed, if
we both suddenly get it.

**Comment by Fabian42** [comment] 2019-03-17 19:26
At least nothing official:
https://developers.google.com/youtube/v3/revision_history

**Comment by deepfriedmind** [comment] 2019-03-17 19:44
Actually, I only get this error when using the `ALL` keyword. If I just input a playlist ID and a channel ID, it finishes without errors but doesn't actually add any videos.

**Comment by Fabian42** [comment] 2019-03-17 20:01
Oh, I didn't notice what report I was commenting on: Yes, I also got this error and it went away when I replaced "all" with the individual channel IDs, then it gave this "property of undefined" error instead. So, @deepfriedmind, yes, I found a potential workaround, maybe it works for you.

**Comment by deepfriedmind** [comment] 2019-03-17 20:36
Like I said, if I just input a playlist ID and a channel ID, it finishes without errors but doesn't actually add any videos. I guess it's the same issue as #26.

**Comment by deepfriedmind** [comment] 2019-03-17 21:15
I looked in the log and noticed `ERROR: API call to youtube.search.list failed with error: Daily Limit Exceeded`. I now see that my dailes queries have risen astronomically and exceed the limit of 1,000,001. I have a trigger set to run the script every hour and haven't been close to reach the limit before.

**Comment by Elijas** [comment] 2019-03-20 08:42
Hi everyone! I'm really sorry to hear that the app is most likely broken at the moment, however I'm currently really busy with my other commitments, although I hope to find some spare time during the upcoming weekends, but count on me for that.

However, one of you created a bounty in Bountify, which will end in 7 days, to fix the recent major bug regarding the API change
https://bountify.co/auto-add-youtube-videos-from-subscribed-channels-to-specific-playlists

If you're a programmer, you can try to tackle it, if you're not, you could reach out to the author to raise the reward, or just spread the word!

**Comment by jcrbcn** [comment] 2019-08-05 19:32
Still no fix for this? Has the YouTube API changed or something?

**Comment by dudemario** [comment] 2019-09-15 23:00
Stuff from Mar 17th is due to YT taking their search down. This should be fixed now so this should no longer pose as an issue. For the first error mentioned above, seems like that code is outdated. Is the issue still there?

**Comment by Capacino** [comment] 2019-09-23 20:29
I get this error as well, and it only happens when i use "ALL" keyword. I also don't get any videos added when i put a channel or playlist id instead of "ALL."

**Comment by dudemario** [comment] 2019-09-24 20:07
Hi @Capacino, thanks for your input.

I'm not too sure why you're still getting this issue, as I can still use the script with no problems.

First off, make sure you've done [this](https://github.com/Elijas/auto-youtube-subscription-playlist-2#q-i-get-this-error-typeerror-second-argument-to-functionprototypeapply-must-be-an-array-line-27-file-)

To help you debug the program, can you please replace the script in your sheet with [this one](https://github.com/Elijas/auto-youtube-subscription-playlist-2/blob/better-error-handling/sheetScript.gs) on my new branch, which has a better error checking and handling. If you don't know how to access the script, on your Google Sheet, go to Tools -> Script Editor. Then, run the function through the Sheets UI as normal, and once it finishes, look at the Debug sheet that will be generated.

**Comment by Capacino** [comment] 2019-09-25 01:06
@dudemario, so when i input your updated script, the error with "ALL" keyword stopped. The first time i ran the script it added some of the videos and seemed like it works. But when i ran it a couple of hours later it gave this error in the logs: https://imgur.com/a/1kb6LyR

**Comment by dudemario** [comment] 2019-09-25 03:40
How many subs do you have? If it's saved, can you also go back in history to see if the debug sheet had an "Acquired subscriptions (number of subs)" that equals the number you have?

In fact, you might have more errors in the debug sheet from before that might expose other bugs, so if you can take a look that'd be great. 

If you don't have that many channels, can you change line 10 to be `var debugFlag_logWhenNoNewVideosFound = true;` to add more logs when running it again hopefully after the quota refills.

**Comment by Capacino** [comment] 2019-09-25 19:39
So i have over 76 on the current youtube account i'm using. When the script ran it did say that it acquired all 76 subscriptions. Then after that it always puts the over quota error. Does the script have a limit to how many videos and/or subscribers it can pull from?

**Comment by dudemario** [comment] 2019-09-25 22:01
How many quota errors do you see? I'll do some testing but If there aren't that many videos it shouldn't pass the quota that fast.

**Comment by JesperDramsch** [comment] 2019-09-26 22:47
I copied the new log script too. Worked real good first time. Then only returns empty.

When I turn the debug flag on, no channel has new video, regardless whether they do or not. (Played around with timestamps too to no avail)

**Comment by Capacino** [comment] 2019-09-29 02:31
So I've been messing around with the number of channels i could get videos from. And currently it's best to avoid using the ALL keyword if you have more than 50+ channels as it takes up too many of the api calls maxing out your quota for the day. Just copying the channel IDs your subbed to is much less calls to the api. The upper limit of what I've tested is 75 channels at 1 previous day timestamp.

**Comment by dudemario** [comment] 2019-09-29 04:15
@JesperDramsch and others, the script is working perfectly due to YouTube's API being a bit broken [as mentioned in this issue](https://github.com/Elijas/auto-youtube-subscription-playlist-2/issues/41), which can be tested using their [API explorer page](https://developers.google.com/youtube/v3/docs/search/list). (This especially affects vids released within the last 24h). I'll see what I can fix in the meantime, but if vids are not getting added, this might be the cause

**Comment by dudemario** [comment] 2019-10-02 21:04
As mentioned in #41 YouTube's API has pretty much been fixed, so the script should be working fine now. @JesperDramsch can you check if you're still encountering the same issue? Pushed a new set of changes to the debug branch (even more logging) so try using this new version.

**Comment by JesperDramsch** [comment] 2019-10-02 21:18
Works again as also mentioned in #41. I'll check out the debug branch

**Comment by JesperDramsch** [comment] 2019-10-02 22:06
@dudemario Checked it out. I like it, except for the proposed change in #45

**Comment by dudemario** [comment] 2019-10-02 22:39
@Capacino Do you still have quota error? If you go to the link that the quota error provides, what's your quota limit?

**Comment by Capacino** [comment] 2019-10-03 00:15
@dudemario No i don't get the quota error anymore. I just split my 400+ subscriptions across 6 google accounts and it works perfectly. I think more than 100 subscribers makes you hit the quota easily.

**Comment by JesperDramsch** [comment] 2019-10-03 00:30
I have 150 subscriptions, but they're not daily vloggers.

**Comment by victorjzsun** [comment] 2019-11-21 01:42
Closing this after implementing changes to script.

**Closed by victorjzsun** 2019-11-21 01:42 UTC
